---
#
# This is the list of all the VLANs that will be defined on Nexus, UCS and OCP
#
# Commenting out the following two variables will skip the iSCSI and/or FC configurations
configure_iscsi: "yes"
# configure_fc: "yes"
#
# Initial FlashArray Configuration, only define this if initial Pure FlashArray setup is required
# initial_fa_config: "yes"
#
# FC-NVMe Configuration, only define this if configure_fc is defined and fc-nvme configuration is required
# ESXi does not support presenting VMFS storage via more than one protocol, so enabling NVMe will override FC connectivity
# Creating a multi-protocol host object should be avoided on the FlashArray when in use with VMware ESXi
# configure_nvme: "yes"
#
# Swap Datastore Configuration, not required for Pure Storage, only left here in case customer already uses swap datastores
# swap_datastore: "yes"
# Enable VSAN trunking between UCS FI and MDS, only set this to yes if configure_fc is set to yes
enable_vsan_trunking: "yes"

# Uncomment and update the the following line to setup Timezone
time_zone: 'America/New_York'
#
# Uncomment and update the the following lines to setup NTP Server(s)
# Note that we are setting up NTP Distribution on the Nexus switches and these are the two Nexus mgmt0 IP addresses that will be used for the other FlashStack equipment.
ntp_servers:
  - ip_address: "10.1.164.254"
#  - ip_address: "192.168.156.136"
ib_mgmt_ntp_servers:                # To be used by ESXi hosts and VMs
  - ip_address: "10.1.164.127"
  - ip_address: "10.1.164.254"
ntp_distribution_nm_cidr: 24

# Uncomment and update the the following lines to setup DNS Server(s)
dns_servers:
  - ip_address: "10.1.164.127"
  - ip_address: "10.1.164.125"

# DNS Domain Name
dns_domain_name: "flashstack.com"


# VLAN Names are adjustable and can be modified in here
#
native_vlan_name: 'Native-Vlan'  # Native VLAN
oob_vlan_name: 'OOB-MGMT-VLAN'  # Out of Band Mgmt VLAN
ib_vlan_name: 'IB-MGMT-VLAN'  # IN BAND Management VLAN
vm_vlan_name: 'VM-Traffic-VLAN'  # VLAN to carry VM traffic on VDS
vmotion_vlan_name: 'vMotion-VLAN'  # vMotion VLAN
iscsiA_vlan_name: 'iSCSI-A-VLAN'  # iSCSI-A VLAN (if needed)
iscsiB_vlan_name: 'iSCSI-B-VLAN'  # iSCSI-B VLAN (if needed)
#
# lan_state should be set to 'present' to configure the objects
# In future, this parameter will be used for deleting the configuration
#
lan_state: 'present'
#
vlan_list:
  - name: "{{ native_vlan_name }}"
    id: '2'
    native: 'yes'
    state: "{{lan_state}}"
  - name: "{{ oob_vlan_name }}"
    id: '15'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ ib_vlan_name }}"
    id: '115'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ vm_vlan_name }}"
    id: '1101'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ vmotion_vlan_name }}"
    id: '1130'
    native: 'no'
    state: "{{lan_state}}"
    # ISCSI A and B VLANs should be deleted or commended out for Fiber-Channel-Only deployments
  - name: "{{ iscsiA_vlan_name }}"
    id: '901'
    native: 'no'
    state: "{{lan_state}}"
    to_storage: 'yes'
    storage_protocol: 'iSCSI'
  - name: "{{ iscsiB_vlan_name }}"
    id: '902'
    native: 'no'
    state: "{{lan_state}}"
    to_storage: 'yes'
    storage_protocol: 'iSCSI'

#
# VLANs definition below will be used to setup trunk ports on Nexus Switches
# all_vlans_list: for vpc_peer_link and UCS FI trunk ports
all_vlans_list: "15,115,1101,901,902,1130"
# storage_vlans_list: for storage ports
storage_vlans_list: "901,902"
# mgmt_vlans_list: for management switch trunk port
mgmt_vlans_list: "15,115"
#
iscsi_vlan_a: "901"
iscsi_vlan_b: "902"
native_vlan_id: "2"
#
vmotion_portgroup: "VMKernel-vMotion"
#
vds_vlan_list:
  - name: "{{ vm_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "192_168_1_NET"
    id: '1101'
    active_uplinks:
      - "Uplink 1"
      - "Uplink 2"
    standby_uplinks: []
  - name: "{{ vmotion_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ vmotion_portgroup }}"
    id: '1130'
    active_uplinks: "Uplink 2"
    standby_uplinks: "Uplink 1"
#
# VSAN Parameters
#
vsan_list:
  - name: 'FlashStack-Fabric-A'
    vsan_id: '100'
    fcoe_vlan: '100'
    fabric: 'A'
  - name: 'FlashStack-Fabric-B'
    vsan_id: '200'
    fcoe_vlan: '200'
    fabric: 'B'
#
#
# Storage FC WWPNs (capture from storage system)
#
fcp_ct0_fc0: '52:4A:93:77:DE:D7:21:00'
fcp_ct1_fc0: '52:4A:93:77:DE:D7:21:10'
fcp_ct0_fc2: '52:4A:93:77:DE:D7:21:02'
fcp_ct1_fc2: '52:4A:93:77:DE:D7:21:12'
#
# Storage FC-NVMe WWPNs (capture from storage system)
#
fcp_ct0_fc1: '52:4A:93:77:DE:D7:21:01'
fcp_ct1_fc1: '52:4A:93:77:DE:D7:21:11'
fcp_ct0_fc3: '52:4A:93:77:DE:D7:21:03'
fcp_ct1_fc3: '52:4A:93:77:DE:D7:21:13'
#
# UCS FC WWPNs (capture from the UCS Service Profiles)
#
ucs_host_01_a: '20:00:00:25:b5:a4:0a:01'
ucs_host_01_b: '20:00:00:25:b5:a4:0b:01'
#
ucs_host_02_a: '20:00:00:25:b5:a4:0a:03'
ucs_host_02_b: '20:00:00:25:b5:a4:0b:03'
#
ucs_host_03_a: '20:00:00:25:b5:a4:0a:05'
ucs_host_03_b: '20:00:00:25:b5:a4:0b:05'
#
# UCS FC-NVMe WWPNs (capture from the UCS Service Profiles)
#
ucs_nvme_host_01_a: '20:00:00:25:b5:a4:0a:00'
ucs_nvme_host_01_b: '20:00:00:25:b5:a4:0b:00'
#
ucs_nvme_host_02_a: '20:00:00:25:b5:a4:0a:02'
ucs_nvme_host_02_b: '20:00:00:25:b5:a4:0b:02'
#
ucs_nvme_host_03_a: '20:00:00:25:b5:a4:0a:04'
ucs_nvme_host_03_b: '20:00:00:25:b5:a4:0b:04'
#
#
# Storage iSCSI Target Interfaces
#
iscsi_ct0_a: '192.168.101.146'
iscsi_ct0_b: '192.168.102.146'
iscsi_ct1_a: '192.168.101.147'
iscsi_ct1_b: '192.168.102.147'
#
# VMware Configurations
# provide the user names and passwords to connect to the ESXi ntp_servers
# and VMware vCenter
#
esxi_username: root
esxi_password: H1ghV0lt!
#
vcenter_dc: FlashStack-DC
vcenter_cluster: FlashStack-Management
#
vcenter_hostname: 10.1.164.110
# e.g. vcenter_hostname: 10.50.160.100
vcenter_username: administrator@vsphere.local
# e.g. vcenter_username: administrator@vsphere.local
vcenter_password: H1ghV0lt!
# e.g. vcenter_password: "cisco!23"
#
# DVS Parameters; user version 7.0.0 for VMware 7.0U2 or above
#
dvs_name: "App_DVS1"
dv_version: "7.0.2"
dv_uplink: "2"
dv_protocol: "lldp"
dv_operation: "both"
# vMotion_vlan_list: "1130"
vMotion_vlan_list:
  - name: "{{ vmotion_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ vmotion_portgroup }}"
    id: '1130'
